앱이름='//android.widget.TextView[@content-desc="롯데카드_개발계"]'
로그인xpath='	/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.Button'
로그인id='com.lcacApp:id/btn_login'
간편번호불일치xpath='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.Button'
간편번호불일치Id='com.lcacApp:id/bt_loca_confirm'
로그인_이름Id='com.lcacApp:id/lcet_mobile_phone_auth_name'
로그인_이름xpath='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.EditText'
로그인_주민번호Id='com.lcacApp:id/et_mobile_phone_auth_front_resident_registration_number'
로그인_주민번호xpath='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.LinearLayout[1]/android.widget.LinearLayout[2]/android.widget.EditText'
로그인_주민뒷자리Id='com.lcacApp:id/ll_mobile_phone_auth_back_resident_registration_number'
로그인_주민뒷자리xpath='//android.widget.LinearLayout[@content-desc="주민등록번호의 뒷자리 하나를 입력하세요"]'
로그인_통신사='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]'
로그인_간편번호_인증요청='com.lcacApp:id/bt_mobile_phone_auth_bottom_auth'
로그인_간편번호_인증요청xpath='/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.RelativeLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.Button'
시작하기_로그인Id='com.lcacApp:id/bt_tutorial_login'
시작하기_로그인xpath='//android.widget.Button[@content-desc="로그인 버튼"]'

고객명='안추도'
생년월일='920124'
주민뒷번호='1'
카드번호='5342929700036003'
카드유효기간='0125'
카드cvc='955'

