q='//android.widget.ImageView[@content-desc="q 비읍"]'
w='//android.widget.ImageView[@content-desc="w 지읃"]'
e='//android.widget.ImageView[@content-desc="e 디귿"]'
r='//android.widget.ImageView[@content-desc="r 기역"]'
p='//android.widget.ImageView[@content-desc="p 에"]'
o='//android.widget.ImageView[@content-desc="o 애"]'
i='//android.widget.ImageView[@content-desc="i 야"]'
u='//android.widget.ImageView[@content-desc="u 여"]'
숫자1='//android.widget.ImageView[@content-desc="1"]'
특수문자변경='//android.widget.ImageView[@content-desc="특수문자변경"]'
특수문자='//android.widget.ImageView[@content-desc="느낌표"]'
입력완료='//android.widget.ImageView[@content-desc="입력완료"]'